name: bbrplus

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bbrplus.yml'
#  schedule:
 #   - cron: '00 01 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 512
        temp-reserve-mb: 128
        root-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
    - name: Checkout
      uses: actions/checkout@main
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff -a
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt update
        sudo -E apt install -y wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev libelf-dev apt-utils lsb-release git build-essential libncurses5-dev gcc-multilib g++-multilib python3 python3-pip python3-ply
        sudo -E apt build-dep -y linux
        sudo -E apt autoremove --purge
        sudo -E apt clean
        sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        sudo -E git config --global core.abbrev auto
    - name: Build
      run: |
          bash build_action.sh
        
    - name: move deb packages to publish
      run: |
          mkdir -p publish
          mv ./*.deb ./publish/
          
    - name: Git push assets to "release" branch
      run: |
          cd publish || exit 1
          ls
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release-6.6.22
          git add -A
          git commit -m "bbrplus"
          git remote add boxtest "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u boxtest release-6.6.22
