name: bbrplus

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bbrplus.yml'
#  schedule:
 #   - cron: '00 00 * * *'
   
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Checkout
        uses: actions/checkout@main

      - name: install dep
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gpg python3-pyquery wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev git lsb vim libelf-dev neofetch python3-pip python3-tk debhelper zstd dpkg-sig

      - name: Build
        run: |
          bash build_action.sh
        
      - name: move deb packages to publish
        run: |
          mkdir -p publish
          mv ./*.deb ./publish/
          
      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          ls
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release-6.6.22
          git add -A
          git commit -m "bbrplus"
          git remote add boxtest "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u boxtest release-6.6.22
