name: bbrplus-arm

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bbrplus-arm.yml'
#  schedule:
 #   - cron: '00 01 * * *'
   
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with: 
          platforms: arm

      - name: Build
        run: |
          sudo bash build_action-arm.sh
        
      - name: move deb packages to publish
        run: |
          mkdir -p publish
          mv ./*.deb ./publish/
          
      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          ls
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release-6.6.44-arm
          git add -A
          git commit -m "bbrplus"
          git remote add boxtest "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u boxtest release-6.6.44-arm
