name: bbrplus

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bbrplus.yml'
#  schedule:
 #   - cron: '00 00 * * *'
   
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:bookworm
    if: github.repository == 'aptx17/boxtest'     
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: 
          bash build_action.sh
          ls
        
      - name: move deb packages to publish
        run:
          cd
          ls
          mkdir -p publish
          mv ./*.deb ./publish/

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions@github.com"
          git checkout -b release
          git add -A
          git commit -m "sync"
          git remote add boxtest "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u boxtest release
